spring.application.name=clientui
server.port=8090

# Configuration Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:9102/eureka/

# Activation de la découverte automatique des services via Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# Permet a Spring Cloud Gateway de decouvrir automatiquement les services enregistres dans Eureka.
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
# Normalise les noms de services en minuscules (evite les problemes de casse)

# Forcer IP locale au lieu du hostname de entreprise
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost