# Nom de l'application pour l'enregistrement dans Eureka
spring.application.name=clientui

# Port du serveur
server.port=8090

# Configuration Eureka
# avant docker
#eureka.client.serviceUrl.defaultZone=http://localhost:9102/eureka/
# Pour plus tard si le service de eureka est security
# eureka.client.serviceUrl.defaultZone=http://discUser:discPassword@localhost:9102/eureka/
# Configuration Eureka (utilise les variables d'environnement) - apres docker
eureka.client.serviceUrl.defaultZone=http://${EUREKA_SERVER_HOST:eureka-server}:${EUREKA_SERVER_PORT:9102}/eureka/

# Activation de la decouverte automatique des services via Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# Permet a Spring Cloud Gateway de decouvrir automatiquement les services enregistres dans Eureka.
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
# Normalise les noms de services en minuscules (evite les problemes de casse)

# Forcer IP locale au lieu du hostname de entreprise
eureka.instance.prefer-ip-address=true
# Avant Docker - actif
#eureka.instance.hostname=localhost
# Apres Docker - inactif - Ne pas definir manuellement le hostname, laissez Docker le gerer

####  DISTRIBUTED TRACING  - SPRING CLOUD SLEUTH - MICROMETER TRACING  ####

# Configuration pour chaque microservice (mgateway, clientui, mpatient, mnotes)

# Configuration des endpoints Actuator
management.endpoints.web.exposure.include=health,info,metrics,beans

# Configuration du tracing distribue
# 100% des traces (reduire en production ex: 0.1 pour 10%)
management.tracing.sampling.probability=1.0

# Configuration Zipkin
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans        obsolete pour Micrometer Tracing
# recommandee pour Micrometer Tracing
# avant docker
#management.tracing.zipkin.endpoint=http://localhost:9411/api/v2/spans
# Ou si Zipkin est dans un container Docker :
management.zipkin.tracing.endpoint=http://${ZIPKIN_SERVER_HOST:zipkin}:9411/api/v2/spans

# Configuration des logs pour inclure les trace ID et span ID
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Niveaux de logs
# Pour mgateway seulement (commentez pour les autres services)
#logging.level.org.springframework.cloud.gateway=DEBUG
# Pour debug le tracing (optionnel)
logging.level.io.micrometer.tracing=DEBUG
logging.level.brave=DEBUG
#Active les logs pour les filtres
logging.level.org.springframework.web.filter=DEBUG
logging.level.org.springframework.boot.web.servlet=DEBUG
logging.level.com.clientui.clientui.filter=DEBUG

#### FEIGN CONFIGURATION ####
feign.micrometer.enabled=true

# Activation de Micrometer Tracing
management.tracing.enabled=true


####  CONFIG REDIS  ####
#spring.redis.host=localhost
#spring.redis.port=6379

# controle le comportement des sessions pour les endpoints de gestion (par exemple, /actuator/health, /actuator/info, etc.)
# if_required (valeur par defaut)
#management.security.sessions=never

####  INFO  ####
#info.app.version=clientui - Version en cours de developpement
#info.app.description=clientui - MicroDiab, application d'analyse du diabete des patients
#info.app.documentation=clientui - Lien vers la documentation de l'application
#info.app.information=clientui - Informations utiles
info.app.version=mrisk - Version under development
info.app.description=mrisk - MicroDiab, diabetes analysis application for patients
#info.app.documentation.swagger=http://localhost:8090/swagger-ui/index.html
info.app.documentation.javadoc=${JAVADOC_URL:http://localhost:8090/apidocs/index.html}

