spring.application.name=clientui
server.port=8090

# Configuration Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:9102/eureka/
# Pour plus tard si le service de eureka est security
# eureka.client.serviceUrl.defaultZone=http://discUser:discPassword@localhost:9102/eureka/

# Activation de la découverte automatique des services via Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# Permet a Spring Cloud Gateway de decouvrir automatiquement les services enregistres dans Eureka.
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
# Normalise les noms de services en minuscules (evite les problemes de casse)

# Forcer IP locale au lieu du hostname de entreprise
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost


####  DISTRIBUTED TRACING  - SPRING CLOUD SLEUTH - MICROMETER TRACING  ####

# Configuration pour chaque microservice (mgateway, clientui, mpatient)

# Configuration des endpoints Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus,tracing

# Configuration du tracing distribué
# 100% des traces (reduire en production ex: 0.1 pour 10%)
management.tracing.sampling.probability=1.0

# Configuration Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
# Ou si Zipkin est dans un container Docker :
# management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Configuration des logs pour inclure les trace ID et span ID
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Niveaux de logs
# Pour mgateway seulement (commentez pour les autres services)
#logging.level.org.springframework.cloud.gateway=DEBUG
# Pour debug le tracing (optionnel)
logging.level.io.micrometer.tracing=DEBUG
logging.level.brave=DEBUG
#Active les logs pour les filtres
logging.level.org.springframework.web.filter=DEBUG
logging.level.org.springframework.boot.web.servlet=DEBUG

####  CONFIG REDIS  ####
#spring.redis.host=localhost
#spring.redis.port=6379

# controle le comportement des sessions pour les endpoints de gestion (par exemple, /actuator/health, /actuator/info, etc.)
# if_required (valeur par defaut)
#management.security.sessions=never

